language: node_js
sudo: false
node_js:
- '0.10'
deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: glSZZ6WIydn2WktQnSPT3qBM5+wGKpxON7BWEz37IPXUt/mzhVc/j6RUrKbKo/rE/dyHd6ileIF8hQCu4GKrg23IpI/2EfZHSVxz7eQAPhANXy1jRJMlZcvefbu74ALhSRKTJPKEzxVEBwAoHW+6MEA3rvJZYPpvaq8Wu0bDvg0=
  app: wstunnel
